apiVersion: apps/v1
kind: Deployment
metadata:
     name: sprinapp-deploy
     namespace: mani-ns
spec:
     replicas: 2
     selector:
           matchLabels:
                app: springapp
     template:
         metadata:
            labels:
                app: springapp
         spec:
            containers:
              - name: springapp
                image: manikantanukala/spring-boot-mongo-app:1
                ports:
                 - containerPort: 8080
                resources:
                   requests:
                       cpu: 200m
                       memory: 128Mi
                   limits:
                       cpu: 400m
                       memory: 256Mi
                env:
                 - name: MONGO_DB_HOSTNAME
                   value: mongoservice
                 - name: MONGO_DB_USERNAME
                   value: db
                 - name: MONGO_DB_PASSWORD
                   value: db@123

---
apiVersion: v1
kind: Service
metadata:
      name: springservice
      namespace: mani-ns
spec:
     type: NodePort
     selector:
           app: springapp
     ports:
      - port: 80
        targetPort: 8080

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
       name: mongo-rs
       namespace: mani-ns
spec:
     selector:
         matchLabels:
            app: mongodb
     template:
           metadata:
                labels:
                   app: mongodb
           spec:
              containers:
                 - name: mongoapp
                   image: mongo
                   ports:
                     - containerPort: 27017
                   resources:
                        requests:
                            cpu: 300m
                            memory: 256Mi
                        limits:
                            cpu: 500m
                            memory: 512Mi
                   env:
                    - name: MONGO_INITDB_ROOT_USERNAME
                      value: db
                    - name: MONGO_INITDB_ROOT_PASSWORD
                      value: db@123


---
apiVersion: v1
kind: Service
metadata:
      name: mongoservice
      namespace: mani-ns
spec:
    type: ClusterIP
    selector:
          app: mongodb
    ports:
     - port: 27017
       targetPort: 27017
